name: Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          chmod +x ./setup.sh
          ./setup.sh
      - name: Run tests
        run: |
          chmod +x ./test.sh
          ./test.sh
