name: Release

on:
  push:
    tags:
      - "*"

jobs:
  package-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          zip kanjigrid_kuuuube_${{ github.ref_name }}.zip *.py config.json

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          draft: true
          files: kanjigrid_kuuuube_${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
